#!/usr/bin/env bash

# shellcheck disable=SC2046
# shellcheck disable=SC2164
cd $(dirname "${BASH_SOURCE[0]}")

# auto update git and restart flask on changes

while true; do
    git fetch
    # shellcheck disable=SC1083
    if [ "$(git rev-parse HEAD)" != "$(git rev-parse @{u})" ]; then
        git reset --hard
        git pull
        echo "Restarting TodoList"
        systemctl restart todolist_nsi.service
    fi
    sleep 10
done